const ADD_NEW_TASK = "ADD_NEW_TASK"
const FETCHED_TASKS = "FETCHED_TASKS"
const DELETE_TASK = "DELETE_TASK"
const UPDATE_TASK = "UPDATE_TASK"

export {ADD_NEW_TASK, FETCHED_TASKS, DELETE_TASK, UPDATE_TASK}
